### ISSUE TITLE
Step-by-step guide to setting up automatic folder icon generation?

### ISSUE THREAD

**Issue by Superpencil** [pond/add_folder_icons#2]
Step-by-step guide to setting up automatic folder icon generation?

**Comment by pond** [comment]
Good idea... I should add this to the Help docs.

Sorry I didn't respond earlier - over a year? Wow. I just didn't see the addition! Thanks for the request :-)

**Comment by pond** [comment]
I added this guide in passing when doing a bug fix for version 3.0.5. I just submitted it for review. If it gets accepted, I'll tag the release and mark this issue closed (implemented).

**Comment by Superpencil** [comment]
😬🎯

**Comment by pond** [comment]
OK, that's all live and in the stores now :-)
